remote scries guide: add warning message
urbit/developers.urbit.org pull request #375
Opened 2023-06-01 09:20 UTC by tinnus-napbus

add warning message about subscriber bug & lack of encryption

2023-06-01 15:45 UTC, jalehman requested changes

2023-06-01 15:45 UTC, jalehman commented on content/guides/additional/remote-scry.md
> +to use remote scries in production userspace code until then.
The fix for this goes out today and does not require an additional kelvin burn. After today's release goes out, this message could be updated to reference the base hash/urbit-os version that has the fix.

2023-06-01 22:36 UTC, jalehman commented on content/guides/additional/remote-scry.md
> +to use remote scries in production userspace code until then.
Where is this used in Clay? Would be great to include a reference to the code that can be used to implement a fallback.

2023-06-02 07:06 UTC, tinnus-napbus commented
ok I have updated with Ted's suggestion. I think probably it's not necessary to include a clay code example cos clay is complex and how you'd implement the solution is relatively intuitive

2023-06-08 12:53 UTC, merged