Document set operations
urbit/developers.urbit.org pull request #483
Opened 2023-08-21 22:31 UTC by sigilante

What do you think?  This could work as a landing page for `++in` or something too.

2023-08-22 00:13 UTC, matthew-levan commented
Excellent illustrations.

2023-08-22 06:42 UTC, tinnus-napbus requested changes
Cool diagrams, looks good apart from my comments - is that syntax meant to invoke LaTeX or something? It seems like it's not working, at least not in the preview

2023-08-22 06:42 UTC, tinnus-napbus commented on content/guides/additional/sets.md
> +A \cup B \equiv \{ x : x \in A \;\textrm{or}\; x \in B \}
this syntax doesn't render properly in all cases

2023-08-22 06:42 UTC, tinnus-napbus commented on content/guides/additional/sets.md
> +[`++put:in`](https://developers.urbit.org/reference/hoon/stdlib/2h#putin) adds an element $x$ to a set $A$.
all cases of the $something$ syntax render as-is. Is that meant to do something different?

2023-08-22 15:01 UTC, sigilante commented
It's LaTeX, but I think we have to use a different invocation on the site come to think of it.

2023-08-22 18:54 UTC, sigilante commented
OK, it's ready with regard to typography.

2023-08-23 10:09 UTC, tinnus-napbus approved these changes

2023-11-06 11:54 UTC, tinnus-napbus commented
redone for new docs site in https://github.com/urbit/docs.urbit.org/pull/32

2023-11-06 11:54 UTC, closed without merging